---
functional:
  - Пользователь должен иметь возможность создать собственную игру
  - Пользователь должен иметь возможность изменить язык программирования после создания игры
  - Пользователь должен иметь возможность подключения к чужой игре
  - Во время игры пользователь должен видеть свой редактор, и редактор противника
  - Во время игры должен отображаться чат игроков
  - Должна быть возможность писать в чат
  - Игрок должен иметь возможность нажать на кнопку "check" неограниченное колличество раз
  - При выходе игрока 1 из игры, игрок 2 должен иметь возможность продолжить игру
  - У игрока 1 при выходе из игры должна быть возможность вернуться в игру, в любой момент до её окончания
  - После того, как любой из игроков находит верное решение, у всех игроков отображается модальное окно, с информацией о том, кто является победителем
  - После окончания игры у игроков должна быть возможность посмотреть на свой написанный код
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Если игрок закрывает вкладку сайта, далее заходит обратно в игру, весь ранее написанный код сохраняется
  - Изменение кода другого игрока должно отображаться корректно, изменения должны происходить онлайн
  - Сообщения в чате не должны ломать интерфейс (HTML-инъекции)
  - Сообщения в чате отображаются в верном порядке
  - Чат обновляется онлайн, новые сообщения отображаются без перезагрузки страницы
