---
functional:
  - Пользователь должен иметь возможность авторизоваться
  - Пользователь должен иметь возможность создать игру
  - Пользователь должен иметь возможность изменить язык программирования после создания игры
  - Пользователь должен иметь возможность подключиться к чужой игре
  - Во время игры пользователь должен видеть свой редактор и редактор противника
  - Во время игры должно отображаться задание
  - Во время игры должен быть доступен чат с возможностью отправки сообщений
  - Игрок должен иметь возможность использовать кнопку "check" неограниченное количество раз
  - При выходе одного игрока второй должен иметь возможность продолжить игру
  - Вышедший игрок должен иметь возможность переподключиться в игру до её завершения
  - После нахождения верного решения должно отображаться модальное окно с информацией о победителе
  - После окончания игры у игроков должна быть возможность просмотреть свой код
  - Победитель должен иметь возможность выйти из игры через кнопку "exit"
  - У победителя после завершения игры кнопка "check" должна быть неактивна
  - Проигравший должен иметь возможность выйти из игры или продолжить доигрывать самостоятельно

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)

implicit:
  - Если игрок закрывает вкладку и возвращается в игру, весь ранее написанный код должен сохраняться
  - Изменения в коде соперника должны отображаться онлайн
  - Сообщения в чате должны отображаться в корректном порядке и не ломать интерфейс (защита от HTML-инъекций)
  - Чат должен обновляться онлайн без перезагрузки страницы
  - Игра может длиться неограниченное время, если не найдено решение
  - После выхода обоих игроков игра должна считаться завершённой и удаляться из памяти
